name: Docker Build

on:
  push:
    branches: [main]  # 只要 push 到 main 分支就會自動執行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t test-build-image .
